---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: admin
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.14.*
spec:
  releaseName: cluster-autoscaler
  chart:
    # Helm Charts: https://github.com/kubernetes/charts/tree/master/stable/cluster-autoscaler
    repository: https://kubernetes-charts.storage.googleapis.com
    name: cluster-autoscaler
    version: 6.2.0
  values:
    image:
      repository: k8s.gcr.io/cluster-autoscaler
      tag: v1.14.3
      pullPolicy: IfNotPresent
    cloudProvider: aws
    podAnnotations:
      iam.amazonaws.com/role: odc-test-stage-odc-eks-autoscaler
    autoDiscovery:
      clusterName: odc-test-stage-odc-eks
    awsRegion: ap-southeast-2
    rbac:
      create: true
    sslCertPath: /etc/kubernetes/pki/ca.crt
    extraArgs:
      scale-down-unneeded-time: "10m"
      balance-similar-node-groups: true
      skip-nodes-with-system-pods: false
