---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: admin
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.chart-image: glob:*
spec:
  releaseName: cluster-autoscaler
  chart:
    # Helm Charts: https://github.com/kubernetes/charts/tree/master/stable/cluster-autoscaler
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: stable/cluster-autoscaler
    version: 6.2.0
  values:
    image:
      tag: "v1.14.6"
    cloudProvider: aws
    podAnnotations:
      iam.amazonaws.com/role: odc-test-stage-odc-eks-autoscaler
    autoDiscovery:
      clusterName: odc-test-stage-odc-eks
    awsRegion: ap-southeast-2
    rbac:
      create: true
    sslCertPath: /etc/kubernetes/pki/ca.crt
    extraArgs:
      scale-down-unneeded-time: "10m"
      balance-similar-node-groups: true
      skip-nodes-with-system-pods: false
