---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube2iam
  namespace: admin
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:*
spec:
  releaseName: kube2iam
  chart:
    # Helm Charts: https://github.com/kubernetes/charts/tree/master/stable/kube2iam
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kube2iam
    version: 2.1.0
  values:
    host:
      iptables: true
      interface: eni+
    rbac:
      create: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
  valuesFrom:
    - configMapKeyRef:
        # Name of the config map, must be in the same namespace as the HelmRelease
        name: kube2iam-cm  # mandatory
        # Key in the config map to get the values from
        key: extraArgs.base-role-arn

