---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: admin
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:0.3.6
spec:
  releaseName: metrics-server
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/stable/metrics-server
    repository: https://kubernetes-charts.storage.googleapis.com
    name: metrics-server
    version: 2.8.9
  values:
    image:
      repository: gcr.io/google_containers/metrics-server-amd64
      tag: 0.3.6
      pullPolicy: IfNotPresent
    rbac:
      create: true
    args:
      - --kubelet-preferred-address-types=InternalIP
      - --logtostderr
